os:
  - linux
  - osx
  - windows

language: go
go:
  - stable
  - 1.x
  - 1.14.x
  - 1.15.x

install: true

services:
  - docker

env:
  - GO111MODULE=on

before_install:
  - go get gotest.tools/gotestsum
  - go get -u github.com/magefile/mage
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew cask install docker
      open --background -a Docker && \
        while ! docker system info > /dev/null 2>&1; do sleep 1; done
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install docker-compose ;
      [Environment]::SetEnvironmentVariable("DOCKER_CLI_EXPERIMENTAL", "true", [EnvironmentVariableTarget]::Machine)
    fi

before_script:
  - go mod verify
  - go mod tidy
  - mage -v format
  - go vet ./...

script:
  - gotestsum --format short-verbose ./...

